name: chat_example
description: Example app demonstrating the chat SDK.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
